name: Armored-Attire
version: '${version}'
main: com.riintouge.armoredattire.ArmoredAttire
api-version: '1.21'
authors: [ Terrenteller ]
depend: [ NBTAPI , ProtocolLib ]

commands:
  attire:
    description: "Alter the cosmetic appearance of an item"
    usage: "/attire (clear|hide|preview|set)"
    clear:
      description: "Remove the cosmetic from the held item"
      usage: "/attire clear"
      permission: permission.node
      permission-message: "You do not have permission to use this command"
    hide:
      description: "Hide the equipment in the given slot"
      usage: "/attire hide <slot>"
      permission: permission.node
      permission-message: "You do not have permission to use this command"
    preview:
      description: "Show the player their cosmetics"
      usage: "/attire preview [on|off]"
      permission: permission.node
      permission-message: "You do not have permission to use this command"
    set:
      description: "Apply a cosmetic to a worn or off hand item"
      usage: "/attire set"
      permission: permission.node
      permission-message: "You do not have permission to use this command"
